--- 
title: "WFC 70: Data Literacy for Wildlife Biologists"
author: "Rob Furrow"
date: "`r Sys.Date()`"
site: bookdown::bookdown_site
---

# Welcome to WFC 70 {-}

The purpose of WFC 70 is to build your data literacy skills, with a focus on using R programming to wrangle, plot, and interpret data. 

This website is a mini-textbook where you can browse the course labs and explore other mini-lessons. Some focus on troubleshooting common mistakes, other on shortcuts for maximum efficiency, and others on more advanced techniques that may enable you to take on additional challenges for  to be a place where we demonstrate solutions to common mistakes, provide more practice, and provide resources to improve your R and data literacy skills. 

This website was created by Learning Assistants! We hope it is of use :)

---

All videos in this website are created by Anthony Roberson. Sections are written by Rosaleen Hernandez with contribution of Rob Furrow. Materials obtained from past WFC 70 courses.  



